pipeline{
    agent{
             node{
                label 'AGENT-1'
             }
    }
    environment {
        Packageversion=""
    }
    stages{
        stage('clone'){
            steps{
                   echo "Already cloned the code to github"
            }
        }
    
    // stage('build'){
    //     steps{
    //          sh """
    //             cd catalogue-ci
    //             npm install
    //          """
    //     }
    // }
        stage('get version'){
            steps{
                script {

                    def readjson=readJSON file: "package.json"
                    packageversion=readjson.version
                    echo "The version of package is : ${packageversion}"
                
                }
            } 
        } 
    }  
    post{
        always{
                  echo "This Pipeline is always runs"
                  deletedir()
        }
        failure{
                  echo "pipeline there is error"
        }
        success{
                  echo "pipeline is success"
        }
    }
}