pipeline {
    agent {
        node {
            label 'agent1'
        }
    }
    options {
        timeout(time:60 , unit:'SECONDS')
    }
    environment {
        greeting='Good morning'
    }
    stages {
        stage('build'){
            steps {
                echo "This stage is for building"
            }
        }
        stage('deploy'){
            steps {
            sh """
                  echo "This stage is for deploy "
                  echo "$greeting"
            """
            }
        }
    }
    post {
        always {
            echo "Above pipeline is to build and deploy code"
        }
        failure{
            echo "pipeline is failed"
        }
        success{
            echo"pipeline is success"
        }
    }
}