pipeline {
    agent {
        node {
            label 'agent1'
        }
    }
    parameters {
        string(name: 'PERSON', defaultValue: 'Jagadeesh', description: 'Who should I say hello to?')

        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')

        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')

        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')

        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }
    options {
        timeout(time:60 , unit:'SECONDS')  // HOURS 
    }
    environment {
        greeting='Good morning'
    }
    stages {
        stage('build'){
            steps {
                echo "This stage is for building"
            }
        }
        stage('deploy'){
            steps {
            sh """
                  echo "This stage is for deploy "
                  echo "$greeting"
            """
            }
        }
        stage('Example Params') {
            steps {
                echo "Hello ${params.PERSON}"

                echo "Biography: ${params.BIOGRAPHY}"

                echo "Toggle: ${params.TOGGLE}"

                echo "Choice: ${params.CHOICE}"

                echo "Password: ${params.PASSWORD}"
            }
        }
    }
    post {
        always {
            echo "Above pipeline is to build and deploy code"
        }
        failure{
            echo "pipeline is failed"
        }
        success{
            echo"pipeline is success"
        }
    }
}